name: env
description: .env files reader part of queen packages
version: 0.0.2-beta
homepage: https://github.com/maxzod/palace
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
