name: encrypto
version: 0.0.1
description: minimal server side dart micro-framework for building REST api easily
homepage: https://github.com/maxzod/palace
environment:
  sdk: ">=2.12.0 <3.0.0"
publish_to: "none"
dependencies:
  queen_env: ^0.0.2-beta
  cryptography: ^2.0.2
  core:
    path: ../core
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
